Tidbeat-master/Tidbeat/Models/Band.cs
using System.ComponentModel.DataAnnotations;

namespace Tidbeat.Models {
    /// <summary>
    /// The band model.
    /// </summary>
    public class Band {
        /// <summary>
        /// The band id.
        /// </summary>
        [Key]
        public string BandId { get; set; }

        /// <summary>
        /// The band name.
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The band's image external URL.
        /// </summary>
        public string? Image { get; set; }

        /// <summary>
        /// The band's genre.
        /// </summary>
        public string? Gener { get; set; }
    }
}

Tidbeat-master/Tidbeat/Controllers/BandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tidbeat.Data;
using Tidbeat.Models;
using Tidbeat.Services;

namespace Tidbeat.Controllers
{
    /// <summary>
    /// Controls all bands.
    /// </summary>
    public class BandsController : Controller {
        private readonly ApplicationDbContext _context;
        private readonly ISpotifyService _spotifyService;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Initializes needed services for the controller.
        /// </summary>
        /// <param name="context">The context of the application.</param>
        /// <param name="spotifyService">The access to the spotify API.</param>
        public BandsController(ApplicationDbContext context, ISpotifyService spotifyService, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _spotifyService = spotifyService;
            _userManager = userManager;
        }

        /// <summary>
        /// Gets all bands from the database.
        /// </summary>
        /// <param name="searchKey">The text to search with.</param>
        /// <param name="gener">The gender of the song.</param>
        /// <param name="order">The order which the info is shown.</param>
        /// <remarks>GET: Bands/</remarks>
        /// <returns>The view with the bands.</returns>
        // GET: Bands
        public async Task<IActionResult> Index([FromQuery] string searchKey, [FromQuery] string gener, [FromQuery] string order)
        {
            TempData["Search"] = searchKey;
            TempData["Gener"] = gener;
            TempData["Order"] = order;
            var results = await _spotifyService.GetSearchBandsbyValuesAsync(searchKey, gener);
            ViewBag.Result = results;
            if (order == "1") 
            {
                ViewBag.Result.Artists.Items = results.Artists.Items.OrderBy(n => n.Name).ToList();
            }
            if (order == "2")
            {
                ViewBag.Result.Artists.Items = results.Artists.Items.OrderByDescending(n => n.Name).ToList();
            }
            if (order == "3")
            {
                ViewBag.Result.Artists.Items = results.Artists.Items.OrderByDescending(n => n.Popularity).ToList();
            }
            if (order == "4")
            {
                ViewBag.Result.Artists.Items = results.Artists.Items.OrderBy(n => n.Popularity).ToList();

            }
            //Alfabeticamnete a-z
            var currentuser = await _userManager.GetUserAsync(User);
            ViewBag.CurrentUser = currentuser;

            if (User != null && User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                var request = HttpContext.Request;
                var currentUrl = string.Format("{0}://{1}", request.Scheme, request.Host);
                TempData["Friends"] = await UtilityClass.SideBarAsync(user.Id, currentUrl);
            }
            return View();

        }

        /// <summary>
        /// Gets the details of a band.
        /// </summary>
        /// <param name="id">The id of the band.</param>
        /// <remarks>GET: Bands/Details/5</remarks>
        /// <returns>The view with the details of the band.</returns>
        // GET: Bands/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var band = await _spotifyService.GetBandAsync(id);
            if (band == null)
            {
                return NotFound();
            }

            var albumAmount = await _spotifyService.GetAmountBandAlbumAsync(id);
            if (albumAmount == null) 
            {
                ViewBag.albumAmount = 0;
            }
            else 
            {
                ViewBag.albumAmount = albumAmount;
            }

            var top3Songs = await _spotifyService.GetTop3SongsAsync(id);
            ViewBag.top3Songs = top3Songs;

            var allPosts = _context.Posts.Include(p => p.User).Include(p => p.Band).Where(p => p.Band != null && p.Band.BandId == id).ToList();
            ViewBag.posts = allPosts;

            var currentuser = await _userManager.GetUserAsync(User);
            ViewBag.CurrentUser = currentuser;

            if (User != null && User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                var request = HttpContext.Request;
                var currentUrl = string.Format("{0}://{1}", request.Scheme, request.Host);
                TempData["Friends"] = await UtilityClass.SideBarAsync(user.Id, currentUrl);
            }
            return View(band);
        }
    }
}

Tidbeat-master/Tidbeat/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.MSIdentity.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json.Linq;
using SpotifyAPI.Web;
using Tidbeat.AuxilliaryClasses;
using Tidbeat.Data;
using Tidbeat.Models;
using Tidbeat.Services;

namespace Tidbeat.Controllers
{
    /// <summary>
    /// Controls the behaviour of the posts of the application.
    /// </summary>
    public class PostsController : Controller {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISpotifyService _spotifyService;
        private readonly IStringLocalizer<PostsController> _localizer;

        /// <summary>
        /// Initializes needed services like the ApplicationDbContext, the UserManager, the SpotifyService and the StringLocalizer.
        /// </summary>
        /// <param name="context">Context of the website</param>
        /// <param name="userManager">The user manager</param>
        /// <param name="spotifyService">The access to the spotify API</param>
        /// <param name="localizer">The language localizer</param>
        public PostsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, ISpotifyService spotifyService, IStringLocalizer<PostsController> localizer)
        {
            _context = context;
            _userManager = userManager;
            _spotifyService = spotifyService;
            _localizer = localizer;
        }

        private static Expression<Func<Post, bool>> PostPasses(string name, string genre, string order) {
            name = (name == null) ? "" : name;

            return p => ((string.IsNullOrEmpty(name) || p.Title.Contains(name) || p.Band.Name.Contains(name) || p.Song.Name.Contains(name))
                        && (string.IsNullOrEmpty(genre) || p.Song.Gener.Contains(genre) || p.Band.Gener.Contains(genre)));
        }



        /// <summary>
        /// Gets all the posts of the application.
        /// </summary>
        /// <returns>All posts of the application.</returns>
        // GET: Posts
        public async Task<IActionResult> Index([FromQuery] string name, [FromQuery] string genre, [FromQuery] string order)
        {
            order = (order == "") ? "newest" : order;
            TempData["genre"] = genre;
            TempData["name"] = name;
            TempData["order"] = order;
            //var songs = await _context.Songs.ToListAsync();
            /*foreach (var song in songs)
            {
                var genres = await _spotifyService.GetGenresOfSong(song.SongId);
                Console.WriteLine("Genres of " + song.Name + ":\n");
                foreach (var _genre in genres)
                {
                    Console.WriteLine($"\t{_genre}");
                }
            }*/
            var offset = 20;
            ViewBag.Offset = offset;

            var results = await _context
                .Posts
                .Include(p => p.User)
                .Include(p => p.Song)
                .Include(p => p.Band)
                .Where(PostPasses(name, genre, order))
                .ToListAsync();
            ViewBag.FilteredPostsCount = results.Count;
            ViewBag.TotalPostsCount = await _context.Posts.CountAsync();

            /* Console.WriteLine("[ Before Ordering ]");
             foreach (var result in results)
             {
                 Console.WriteLine($"Initial Result: Name({result.Title}), Date({result.CreationDate})");
             }*/
            if (!string.IsNullOrEmpty(genre)) {
                results = results.Where(p => (p.Band?.Gener?.Contains(genre) ?? false) || (p.Song?.Gener?.Contains(genre) ?? false)).ToList(); 
            }
            switch (order)
            {
                case "a-z":
                    results = results.OrderBy(p => p.Title).ToList();
                    break;
                case "oldest":
                    results = results.OrderBy(p => p.CreationDate).ToList();
                    break;
                case "z-a":
                    results = results.OrderByDescending(p => p.Title).ToList();
                    break;
                case "newest":
                    results = results.OrderByDescending(p => p.CreationDate).ToList();
                    break;
            }
            /*
            Console.WriteLine("[ After Ordering ]");
            foreach (var result in results)
            {
                Console.WriteLine($"Posterior Result: Name({result.Title}), Date({result.CreationDate})");
            }*/
            var currentuser = await _userManager.GetUserAsync(User);
            ViewBag.CurrentUser = currentuser;

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                var request = HttpContext.Request;
                var currentUrl = string.Format("{0}://{1}", request.Scheme, request.Host);
                TempData["Friends"] = await UtilityClass.SideBarAsync(user.Id, currentUrl);
            }
            return View(results.Take(offset));
        }

        public async Task<IActionResult> getData(string name, string genre, string order, int offset = 0)
        {
            order = (order == "") ? "newest" : order;
            TempData["genre"] = genre;
            TempData["name"] = name;
            TempData["order"] = order;
            //var songs = await _context.Songs.ToListAsync();
            /*foreach (var song in songs)
            {
                var genres = await _spotifyService.GetGenresOfSong(song.SongId);
                Console.WriteLine("Genres of " + song.Name + ":\n");
                foreach (var _genre in genres)
                {
                    Console.WriteLine($"\t{_genre}");
                }
            }*/

            var results = await _context
                .Posts
                .Include(p => p.User)
                .Include(p => p.Band)
                .Include(p => p.Song)
                .Where(PostPasses(name, genre, order))
                .ToListAsync();

            /* Console.WriteLine("[ Before Ordering ]");
             foreach (var result in results)
             {
                 Console.WriteLine($"Initial Result: Name({result.Title}), Date({result.CreationDate})");
             }*/
            if (!string.IsNullOrEmpty(genre))
            {
                results = results.Where(p => (p.Band?.Gener?.Contains(genre) ?? false) || (p.Song?.Gener?.Contains(genre) ?? false)).ToList();
            }
            switch (order)
            {
                case "a-z":
                    results = results.OrderBy(p => p.Title).ToList();
                    break;
                case "oldest":
                    results = results.OrderBy(p => p.CreationDate).ToList();
                    break;
                case "z-a":
                    results = results.OrderByDescending(p => p.Title).ToList();
                    break;
                case "newest":
                    results = results.OrderByDescending(p => p.CreationDate).ToList();
                    break;
            }
            return PartialView("_PostListPartial", results.Skip(offset).Take(20));
        }

        /// <summary>
        /// Gets the details of a post. If the post is not found, it returns a 404 error.
        /// </summary>
        /// <remarks>GET: Posts/Details/{id}</remarks>
        /// <param name="id">The id of the post.</param>
        /// <returns>The details page of a single post.</returns>
        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.Include(user => user.User).Include(band => band.Band).Include(song => song.Song)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }
            if (post.Song != null)
            {
                ViewBag.urlSong = _spotifyService.GetSongAsync(post.Song.SongId).Result.PreviewUrl;
            }
            ViewBag.fetchCommentsCount = 15;
            ViewBag.currentUser = await _userManager.GetUserAsync(User);
            ViewBag.commentsPosts = _context.Comment.Include(user => user.User).Where(s => s.post.PostId == post.PostId).Take((int) ViewBag.fetchCommentsCount).ToList();
            ViewBag.totalCommentCount = _context.Comment.Include(user => user.User).Where(s => s.post.PostId == post.PostId).Count();

            var currentuser = await _userManager.GetUserAsync(User);
            ViewBag.CurrentUser = currentuser;

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                var request = HttpContext.Request;
                var currentUrl = string.Format("{0}://{1}", request.Scheme, request.Host);
                TempData["Friends"] = await UtilityClass.SideBarAsync(user.Id, currentUrl);
            }

            return View(post);
        }

        public async Task<IActionResult> FetchMoreComments(int postId, int commentCount, int skipCount) {
            var comments = await _context.Comment.Include(user => user.User).Where(s => s.post.PostId == postId).Skip(skipCount).Take(commentCount).ToListAsync();
            ViewData["currentUser"] = await _userManager.GetUserAsync(User);
            return PartialView("_CommentListPartial", comments);
        }

        
        /// <summary>

Tidbeat-master/Tidbeat/Views/Bands/Details.cshtml
@model SpotifyAPI.Web.FullArtist
@using Tidbeat.Services
@using SpotifyAPI.Web
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{
    ViewData["Title"] = "Details";
    var imageUrl = Model.Images.Count != 0 ? Model.Images[0].Url : "../../images/Empty_Artist_Image.png";
    var spotifyPageURL = SpotifyService.UrlBand + Model.Id;
    List<Post> allPosts = ViewBag.posts;
}

<div>
    @{
        await Html.RenderPartialAsync("_Sidebar");
    }
</div>

<!--All music info goes here-->
<div class="container-fluid row w-100 d-flex flex-column flex-lg-row mx-0">
    <div class="d-flex flex-column col-lg-6 col-md-12 vh-100-minus-navbar border-lg-end pe-1">
        <div class="mt-5 pt-5 mb-3 d-flex flex-column align-items-center justify-content-center justify-content-lg-start">
            <h4 class="ms-2 text-dark fw-bold">@Localizer["band_artist"]:</h4>
            <div class="text-primary fw-bold"> @Model.Name</div>
        </div>
        <hr/>
        <div class="d-flex flex-column flex-xl-row justify-content-lg-start align-items-center">
            <a href="@spotifyPageURL" target="_blank">
                <img src="@imageUrl" height="200" class="btn btn-outline-primary border-0 p-1" />
            </a>
            <div class="ms-2 text-start w-100">
                <div class="d-flex flex-column text-start mb-3">
                    <div class="text-dark fw-bold">@Localizer["top_3"]:</div>
                    @foreach (FullTrack track in ViewBag.top3Songs) {
                        <div class="d-flex flex-row w-50">
                            <a href=@Url.Action("Details", "Songs", new { id = track.Id }) class="text-nowrap overflow-hidden text-truncate text-primary fw-bold ps-2">@track.Name</a>
                        </div>
                    }
                </div>
                <hr/>
                <div class="d-flex flex-row">
                    <div class="text-dark fw-bold">@Localizer["followers"]:</div>
                    <div class="text-primary ms-2">@Model.Followers.Total</div>
                </div>
                <div class="d-flex flex-row">
                    <div class="text-dark fw-bold">@Localizer["released_albums"]:</div>
                    <div class="text-primary ms-2">@ViewBag.albumAmount</div>
                </div>
            </div>
        </div>
        <hr style="height: 1px"/>
        <div class="d-flex align-items-lg-start flex-column mt-1">
            <div>@Localizer["post_amount"]: 0</div>
        </div>
        
    </div>

    <!--All posts goes here-->
    <div class="col-lg-6 col-md-12 mt-5 pt-5 scrollable-posts">
        <div class="d-flex justify-content-center mb-2 flex-column">
            <div class="fs-3 me-4">@Localizer["posts"]</div>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="bottom-0 end-0 post-btn-center-lg me-4 mb-4 btn btn-primary" asp-controller="Posts" asp-action="Create" asp-route-Idband="@Model.Id">
                    @Localizer["create_post"]
            </a>
            }
        </div>
        @if (allPosts.Count == 0) {
            <div>@Localizer["no_posts"]</div>
            <img src="~/images/NoPostsImage.png" height="120" class="mt-5" />
        }
        @foreach (Post post in allPosts) {
            <a class="text-decoration-none text-black" href="@Url.Action("Details", "Posts", new { id = post.PostId })">
                <div class="d-flex align-items-center border-2 border-primary p-1 rounded mb-2 hover-background-grey" style="box-shadow: 0 8px 15px -8px rgba(0, 0, 0, 0.4);">
                    <div class="border-end border-2 border-primary pe-2">
                        <div>
                        @if (post.User.Email == Configurations.InvalidUser.Email) {
                            @Localizer["[deleted]"]
                        }
                        else {
                            string personName = post.User.FirstAndLastName();
                            if (personName.Length > 15) {
                                personName = personName.Substring(0, 15);
                                personName += "...";
                            }
                            @personName
                        }
                        </div>
                        <div class="fs-7">@Localizer["created_in"]: @post.CreationDate.Date.ToString("dd/MM/yyyy")</div>
                    </div>
                    <div class="ms-2">@post.Title</div>
                </div>
            </a>
            }
    </div>
</div>

Tidbeat-master/Tidbeat/Views/Bands/Index.cshtml
@using Tidbeat.Controllers
@using Tidbeat.Services
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;
@inject ISpotifyService SpotifyService
@using System.Web

@{
    ViewData["Title"] = "Bands Page";
    Console.WriteLine("Total de Items: " + ViewBag.Result.Artists.Items);
    var gender = TempData["Gener"]?.ToString();
}

<div>
    @{
        await Html.RenderPartialAsync("_Sidebar");
    }
</div>

<div class="mt-4 pt-5">
    <div class="mx-3">
        <div id="filter" class="pb-2">
            <div class="display-6 text-primary text-left d-flex w-2">@Localizer["filters"]</div>
            <div class="d-flex flex-row flex-wrap w-md-100 flex-md-nowrap">
                <div class="input-group d-flex flex-column px-3 flex-grow-1">
                    <div class="text-start">@Localizer["name"]:</div>
                    <input value="@TempData?["Search"]" type="search" id="formSearching" class="w-100 rounded form-control form-outline d-flex flex-row" placeholder="@Localizer["search"]" />
                </div>
                <div class="input-group d-flex flex-column px-3 flex-grow-1">
                    <div class="align-self-start">@Localizer["gender"]:</div>
                    <div class="form-outline d-flex flex-row">
                        <select class="form-control w-100" id="formGender" name="formGender">
                            <!option selected value="">@Localizer["pick_gender"]</!option>
                            <!option value="rock" @(gender == "rock" ? "selected" : "")>@Localizer["rock"]</!option>
                            <!option value="pop" @(gender == "pop" ? "selected" : "")>@Localizer["pop"]</!option>
                            <!option value="kids" @(gender == "kids" ? "selected" : "")>@Localizer["children"]</!option>
                            <!option value="funk" @(gender == "funk" ? "selected" : "")>@Localizer["funk"]</!option>
                            <!option value="classical" @(gender == "classical" ? "selected" : "")>@Localizer["classical"]</!option>
                            <!option value="country" @(gender == "country" ? "selected" : "")>@Localizer["country"]</!option>
                            <!option value="dance" @(gender == "dance" ? "selected" : "")>@Localizer["dance"]</!option>
                            <!option value="metal" @(gender == "metal" ? "selected" : "")>@Localizer["metal"]</!option>
                            <!option value="disco" @(gender == "disco" ? "selected" : "")>@Localizer["disco"]</!option>
                            <!option value="folk" @(gender == "folk" ? "selected" : "")>@Localizer["folk"]</!option>
                            <!option value="hip-hop" @(gender == "hip-hop" ? "selected" : "")>@Localizer["hip_hop"]</!option>
                            <!option value="indian" @(gender == "indian" ? "selected" : "")>@Localizer["indian"]</!option>
                            <!option value="k-pop" @(gender == "k-pop" ? "selected" : "")>@Localizer["k_pop"]</!option>
                            <!option value="punk" @(gender == "punk" ? "selected" : "")>@Localizer["punk"]</!option>
                            <!option value="piano" @(gender == "piano" ? "selected" : "")>@Localizer["piano"]</!option>
                            <!option value="reggae" @(gender == "reggae" ? "selected" : "")>@Localizer["reggae"]</!option>
                            <!option value="techno" @(gender == "techno" ? "selected" : "")>@Localizer["techno"]</!option>
                        </select>
                    </div>
                </div>
                <div class="input-group d-flex flex-column px-3 flex-grow-1 rounded">
                    <div class="align-self-start">@Localizer["order"]:</div>
                    <select class="form-control w-100 rounded" id="Ordere" name="Orderby">
                        <!option value="1" @(TempData["Order"]?.ToString() == "1" ? "selected" : "")>@Localizer["alfabetically_a_to_z"]</!option>
                        <!option value="2" @(TempData["Order"]?.ToString() == "2" ? "selected" : "")>@Localizer["alfabetically_z_to_a"]</!option>
                        <!option value="3" @(TempData["Order"]?.ToString() == "3" ? "selected" : "")>@Localizer["more_popular"]</!option>
                        <!option value="4" @(TempData["Order"]?.ToString() == "4" ? "selected" : "")>@Localizer["less_popular"]</!option>
                    </select>
                </div>
                <div class="align-self-center px-3 pt-3 pt-md-2">
                    <button class="btn btn-primary">
                        <img id="imgBand" class="no-padding align-self-center px-3" src="~/images/SearchIcon.png" height="37" width="45" onclick="actualEvent()" />
                    </button>
                </div>
            </div>
        </div>
        <div class="border border-1 border-light-grey my-4"></div>
        <div>
            @if (ViewBag.Result.Artists.Items.Count > 0)
            {
                <h2 class="d-flex">Bandas e Artistas</h2>
                @foreach (var item in ViewBag.Result.Artists.Items)
                {
                    <a href="@Url.Action("Details", "Bands", new { id = item.Id })" id="@item.Uri" class="hover-background-grey text-decoration-none text-black border-3 border-primary rounded mt-2 d-inline-flex flex-wrap align-content-center mx-2 mx-md-5 w-50 w-sm-25 flex-lg-row flex-column" style="box-shadow: 0 8px 15px -8px rgba(0, 0, 0, 0.4);">
                            @if (item.Images.Count != 0) {
                                <img src="@item.Images[0].Url" alt="@item.Name" width="100" height="100">
                            } else {
                                <img src="~/images/Empty_Artist_Image.png" alt="@item.Name" width="100" height="100">
                            }
                            <div class="text-lg-start text-center justify-content-start align-content-start align-self-center font-weight-bold w-50 flex-column ml-2">
                                <div class="text-lg-start text-center justify-content-start align-content-start align-self-center font-weight-bold w-100">@item.Name</div>
                                <div class="text-lg-start text-center justify-content-start align-content-start align-self-center font-weight-bold w-100 opacity-50">
                                    @if (item.Genres.Count > 0)
                                    {
                                        var genreTextStart = Localizer["genders"].Value + ":";
                                        <div class="flex-column">
                                            <span class="font-weight-bold">@genreTextStart</span>
                                            <br/>
                                            <div class="">
                                            @for (int i = 0; i < 2; i++) 
                                            {
                                                if (item.Genres.Count > i)
                                                {
                                                    <div class="px-1">
                                                        @(" " + item.Genres[i])
                                                    </div>
                                                }
                                                }
                                            </div>
                                        </div>
                                    }</div>
                            </div>
                        </a>
                }
            }else
            {
                <div class="text-danger" id="Danger">@Localizer["no_band"]</div>
            }
        </div>
    </div>
</div>
<script>
        function actualEvent() {
            let inputOrder = document.getElementById("Ordere");
            let inputGener = document.getElementById("formGender");
            let inputSearch = document.getElementById("formSearching");
            let path = window.location.href.split("?")[0];
            if (inputSearch.value || inputGener.value || inputOrder.value) {
                path += "?";
                let params = new URLSearchParams({
                    searchKey: inputSearch.value,
                    gener: inputGener.value,
                    order: inputOrder.value,
                })
                path += params.toString();
                console.log(window.location.href)
                window.location.href = path;
            }
            event.preventDefault();
        }
        document.getElementById("filter").addEventListener("keypress", function (event) {
            if (event.key === "Enter") {
                let focusElement = document.activeElement;
                let inputOrder = document.getElementById("Ordere");
                let inputGener = document.getElementById("formGender");
                let inputSearch = document.getElementById("formSearching");
            if (inputGener === focusElement || inputOrder === focusElement || inputSearch === focusElement) {
                    //only if one of the elements is higthligthed
                    event.preventDefault();
                    actualEvent();
                }
            }
        }
        )
</script>
<style>
    #imgBand {
        cursor: pointer;
    }
</style>